### ISSUE TITLE
Integration with smina

### ISSUE THREAD

**Issue by spadavec** [oddt/rfscorevs#3]
Fantastic work! Are these scoring functions available/able to be integrated with Smina, the fork of vina that allows for use of custom scoring functions?

**Comment by mwojcikowski** [comment]
Since you've closed the issue I guess you have found an answer yourself. But here is an answer, for the future reference.

The smina allows you to use a "custom" scoring function in a sense that you can employ your own weights for selected subset of many implemented descriptors/partial energies etc. This is little known fact that Autodock Vina has many of those, but during calibration only a subset of 5 of them was selected for the final score. But other than that it does not allow to plug in anything "external".

Back to RF-Score-VS, you can't plug it in directly to smina, rather rescore the docked conformations.
